// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLeg8FLqN8uqHRP5mtsLx_7Wj9MDhAxJE',
    appId: '1:401348147522:web:27c40e4742e57649faf0db',
    messagingSenderId: '401348147522',
    projectId: 'eventapp-eacc6',
    authDomain: 'eventapp-eacc6.firebaseapp.com',
    storageBucket: 'eventapp-eacc6.firebasestorage.app',
    measurementId: 'G-089D1YBPZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TrWq2vRTwdvVdr6-YSazIlMg6aFTd-E',
    appId: '1:401348147522:android:5f5c9e2176d9e6a8faf0db',
    messagingSenderId: '401348147522',
    projectId: 'eventapp-eacc6',
    storageBucket: 'eventapp-eacc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_8FUW-GpYzzwlGmGI-VnlkHgczccvY4',
    appId: '1:401348147522:ios:e3998e522dc8d886faf0db',
    messagingSenderId: '401348147522',
    projectId: 'eventapp-eacc6',
    storageBucket: 'eventapp-eacc6.firebasestorage.app',
    iosBundleId: 'com.example.eventapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_8FUW-GpYzzwlGmGI-VnlkHgczccvY4',
    appId: '1:401348147522:ios:e3998e522dc8d886faf0db',
    messagingSenderId: '401348147522',
    projectId: 'eventapp-eacc6',
    storageBucket: 'eventapp-eacc6.firebasestorage.app',
    iosBundleId: 'com.example.eventapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLeg8FLqN8uqHRP5mtsLx_7Wj9MDhAxJE',
    appId: '1:401348147522:web:ca370fdd3aa0c4bafaf0db',
    messagingSenderId: '401348147522',
    projectId: 'eventapp-eacc6',
    authDomain: 'eventapp-eacc6.firebaseapp.com',
    storageBucket: 'eventapp-eacc6.firebasestorage.app',
    measurementId: 'G-2YJ5C2CSD0',
  );
}
